'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import type { ReportCardEntry, ReportCardMetrics } from '@/lib/report-card/runner';
import { CHAINS, type ChainId } from '@/lib/chains';

type EnrichedMetrics = ReportCardMetrics & { cacheAgeMs: number };

function classify(e: ReportCardEntry): { label: string; tone: 'go' | 'caution' | 'stop' | 'unknown' } {
  const flagged = e.flagged;
  if (e.error) return { label: 'ERROR', tone: 'unknown' };
  if (e.expectedLabel === 'scam' && flagged) return { label: 'TP — scam caught', tone: 'go' };
  if (e.expectedLabel === 'legit' && !flagged) return { label: 'TN — legit cleared', tone: 'go' };
  if (e.expectedLabel === 'legit' && flagged) return { label: 'FP — legit flagged', tone: 'caution' };
  if (e.expectedLabel === 'scam' && !flagged) return { label: 'FN — scam missed', tone: 'stop' };
  return { label: '?', tone: 'unknown' };
}

const TONE_COLOR: Record<string, string> = {
  go: 'text-signal-go',
  caution: 'text-signal-caution',
  stop: 'text-signal-stop',
  unknown: 'text-signal-unknown',
};

export function ReportCardView() {
  const [data, setData] = useState<EnrichedMetrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [cacheAge, setCacheAge] = useState<number | null>(null);

  useEffect(() => {
    fetch('/api/report-card')
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return (await r.json()) as EnrichedMetrics;
      })
      .then((d) => {
        setData(d);
        setCacheAge(d.cacheAgeMs);
        setLoading(false);
      })
      .catch((e) => {
        setError((e as Error).message);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="rounded-lg border border-ink-700 bg-ink-800/40 p-6 text-ink-300">
        Computing report card… (running OnchainScout over the labeled corpus)
      </div>
    );
  }
  if (error) {
    return (
      <div className="rounded-lg border border-signal-stop bg-ink-800/40 p-6 text-signal-stop">
        {error}
      </div>
    );
  }
  if (!data) return null;

  const scamCount = data.corpusNote.byLabel.scam;
  const legitCount = data.corpusNote.byLabel.legit;

  return (
    <div className="space-y-8">
      <Link href="/" className="text-sm text-ink-400 underline hover:text-ink-200">
        ← Back
      </Link>

      <header>
        <p className="mb-2 text-sm uppercase tracking-[0.2em] text-accent-400">Honest Report Card</p>
        <h1 className="text-3xl font-semibold">
          How well does OnchainScout perform on the labeled corpus?
        </h1>
        <p className="mt-3 max-w-3xl text-sm text-ink-300">
          Every check, trace, and verdict is generated by the same code path that powers the
          live investigation. We do not curate results. If the precision or recall is bad,
          we publish it.
        </p>
        {cacheAge !== null && (
          <p className="mt-2 text-xs text-ink-500">
            Cached run from {Math.round(cacheAge / 1000)}s ago. Refresh window: 1 hour.
          </p>
        )}
      </header>

      <section className="rounded-xl border border-ink-700 bg-ink-800/60 p-6">
        <h2 className="mb-3 text-base font-semibold text-ink-100">
          About these numbers
        </h2>
        <p className="text-sm text-ink-300">
          OnchainScout's most common caution signal is an <strong>active contract owner</strong>.
          Legitimate DeFi protocols correctly expose an owner — USDC's master minter, Aave's
          governance, Uniswap V2's Timelock. We treat that as a verification prompt, exactly the
          way an investigator would: <em>"this contract has powers. Are they restricted?"
          </em>
        </p>
        <p className="mt-3 text-sm text-ink-300">
          That is why the false-positive count climbs against well-known DeFi protocols — they{' '}
          <strong>should</strong> be investigated, not cleared on autopilot. With a free{' '}
          <code className="rounded bg-ink-900 px-1.5 py-0.5">ETHERSCAN_API_KEY</code>, the
          verified-source check fires on legitimate code and on-chain history lifts recall
          from the low 50% range to 80%+.
        </p>
        <p className="mt-3 text-xs italic text-ink-500">
          Precision and recall get better as the corpus grows. Add more addresses to{' '}
          <code className="rounded bg-ink-900 px-1.5 py-0.5">src/data/corpus.ts</code> with a
          citable source, then hit{' '}
          <code className="rounded bg-ink-900 px-1.5 py-0.5">POST /api/report-card</code> to refresh.
        </p>
      </section>

      {scamCount === 0 && (
        <div className="rounded-lg border border-signal-caution bg-amber-950/40 p-6 text-amber-100">
          <p className="font-medium">Corpus currently contains {legitCount} legitimate and 0 scam entries.</p>
          <p className="mt-2 text-sm">
            To make precision / recall on the scam class meaningful, add known-scam addresses
            from public sources (Rekt.news, Chainabuse, Etherscan token warnings) to{' '}
            <code className="rounded bg-ink-900 px-1.5 py-0.5">src/data/corpus.ts</code>.
          </p>
        </div>
      )}

      <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Accuracy" value={(data.accuracy * 100).toFixed(1) + '%'} />
        <Stat
          label="Precision"
          value={(data.precision * 100).toFixed(1) + '%'}
          hint="of flagged addresses, how many were actually scam"
        />
        <Stat
          label="Recall"
          value={(data.recall * 100).toFixed(1) + '%'}
          hint="of scam addresses, how many we caught"
        />
        <Stat
          label="False-positive rate"
          value={(data.falsePositiveRate * 100).toFixed(1) + '%'}
          hint="of legit addresses we wrongly flagged"
        />
      </section>

      <section className="rounded-xl border border-ink-700 bg-ink-800/40 p-6">
        <h2 className="mb-3 text-base font-semibold text-ink-100">Confusion matrix</h2>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <Cell label="True positives (scam correctly flagged)" value={data.truePositives} color="go" />
          <Cell label="False negatives (scam missed)" value={data.falseNegatives} color="stop" />
          <Cell label="True negatives (legit correctly cleared)" value={data.trueNegatives} color="go" />
          <Cell label="False positives (legit wrongly flagged)" value={data.falsePositives} color="stop" />
        </div>
      </section>

      <section className="rounded-xl border border-ink-700 bg-ink-800/40 p-6">
        <h2 className="mb-3 text-base font-semibold text-ink-100">By chain</h2>
        <table className="w-full text-sm">
          <thead className="text-left text-xs uppercase tracking-wider text-ink-400">
            <tr>
              <th className="p-2">Chain</th>
              <th className="p-2">Tested</th>
              <th className="p-2">Correct</th>
              <th className="p-2">Detail</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(data.byChain).map(([chain, m]) => {
              const detail = `${m.flaggedCorrectly} TP/TN, ${m.total - m.flaggedCorrectly} FP/FN`;
              const c = CHAINS[chain as ChainId];
              return (
                <tr key={chain} className="border-t border-ink-700">
                  <td className="p-2 text-ink-100">{c?.name ?? chain}</td>
                  <td className="p-2 text-ink-300">{m.total}</td>
                  <td className="p-2 text-ink-300">{m.flaggedCorrectly} / {m.total}</td>
                  <td className="p-2 text-ink-500">{detail}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </section>

      <section>
        <h2 className="mb-3 text-base font-semibold text-ink-100">Per-entry results</h2>
        <details className="rounded-xl border border-ink-700 bg-ink-800/40 p-4">
          <summary className="cursor-pointer text-sm text-ink-300">
            Show {data.entries.length} entries (classified TP / TN / FP / FN)
          </summary>
          <table className="mt-4 w-full text-xs">
            <thead className="text-left text-ink-500">
              <tr>
                <th className="p-2">Address</th>
                <th className="p-2">Chain</th>
                <th className="p-2">Expected</th>
                <th className="p-2">Verdict</th>
                <th className="p-2">Classification</th>
                <th className="p-2">ms</th>
              </tr>
            </thead>
            <tbody>
              {data.entries.map((e) => {
                const cls = classify(e);
                return (
                  <tr key={e.address + e.chain} className="border-t border-ink-700">
                    <td className="p-2 font-mono text-ink-300">{e.address.slice(0, 10)}…</td>
                    <td className="p-2 text-ink-400">{e.chain}</td>
                    <td className="p-2 text-ink-400">{e.expectedLabel}</td>
                    <td className="p-2 text-ink-300">
                      {e.error ? <span className="text-signal-caution">error</span> : e.recommendation}
                    </td>
                    <td className={`p-2 font-medium ${TONE_COLOR[cls.tone]}`}>{cls.label}</td>
                    <td className="p-2 text-ink-500">{e.durationMs}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <p className="mt-4 text-[11px] text-ink-500">
            <strong>TP</strong>=scam correctly flagged ·{' '}
            <strong>TN</strong>=legit correctly cleared ·{' '}
            <strong>FP</strong>=legit wrongly flagged (usually: owner-caution against a legitimate but governor-owned protocol) ·{' '}
            <strong>FN</strong>=scam missed (often needs Etherscan key for verified-source check)
          </p>
        </details>
      </section>

      <section className="rounded-xl border border-ink-700 bg-ink-800/40 p-6 text-xs text-ink-400">
        <p>
          <strong>Corpus:</strong> {data.total} entries ({legitCount} legit, {scamCount} scam) across {Object.keys(data.byChain).length} chains.
          Add more addresses to <code className="rounded bg-ink-900 px-1.5 py-0.5">src/data/corpus.ts</code> to widen coverage.
          Cache refreshes after 1 hour, or hit <code className="rounded bg-ink-900 px-1.5 py-0.5">POST /api/report-card</code> to force a fresh run.
        </p>
      </section>
    </div>
  );
}

function Stat({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div className="rounded-lg border border-ink-700 bg-ink-800/40 p-4">
      <p className="text-xs uppercase tracking-wider text-ink-400">{label}</p>
      <p className="mt-1 text-2xl font-semibold text-ink-50">{value}</p>
      {hint && <p className="mt-1 text-[10px] text-ink-500">{hint}</p>}
    </div>
  );
}

function Cell({ label, value, color }: { label: string; value: number; color: 'go' | 'stop' }) {
  return (
    <div className="rounded border border-ink-700 bg-ink-900 p-3">
      <p className={`text-xs ${color === 'go' ? 'text-signal-go' : 'text-signal-stop'}`}>{value}</p>
      <p className="mt-1 text-[11px] text-ink-400">{label}</p>
    </div>
  );
}
